### PR TITLE
Update CMakeLists.txt to compile UFS APP ATMAERO

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Update top-level `CMakeLists.txt` to build `UFS_APP=ATMAERO`. I tested building this on macOS (Monterey, apple-clang+gfortran) and on AWS Parallelcluster (Ubuntu 20, Intel).

Notes:
1. There is no `ctest` yet for this setup. It would be good if the COMPO team could add this. @cmgas and @climbfuji can assist.
2. Any necessary updates to components of `ufs-bundle` (e.g. `ufs-weather-model`, `fv3-jedi`) have already been pushed to the corresponding branches:
    - https://github.com/JCSDA-internal/fv3-jedi/commit/52e14393f08748922872c641aab85b343bc2a941
    - https://github.com/climbfuji/ufs-weather-model/commit/bd64387cc4c8a82028d83b6ee3a72bd80b72a58f (with additional PRs for its submodules)

## Definition of Done

We should merge this PR if it doesn't affect building `UFS_APP=ATM` for them. (It doesn't for me)

### Issue(s) addressed

- Working on https://github.com/JCSDA/ufs-bundle/issues/8

## Dependencies

This is a much bigger task ... see https://github.com/JCSDA/ufs-bundle/issues/19. Nonetheless, we should merge this PR here.

## Impact

n/a

### CODE REVIEW

**Review by mer-a-o — DISMISSED** [review]
Changes look good. Can I test it using skylab-v3 modules on any of the HPCs?
README needs to be updated too.

**Comment by jeromebarre** [comment]
I tried on Orion:
`ecbuild --build=debug -DUFS_APP=ATMAERO .. 2>&1 | tee log.ecbuild`
I got this error:
```
CMake Error at CMakeLists.txt:47 (find_package):
  Could not find a configuration file for package "FMS" that is compatible
  with requested version "2022.04".

  The following configuration files were considered but not accepted:

    /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-3.0.0-gnu-10.2.0/install/gcc/10.2.0/fms-release-jcsda-ulfb7ay/lib64/cmake/fms/fms-config.cmake, version: 2020.4.0
```

Do we need to load something specific for testing? This relates to @mer-a-o 's comment above.

**Comment by climbfuji** [comment]
After loading the `jedi-ufs-env` modules from the latest spack-stack release, you need to swap out the `fms` module. That is described in full detail in the top-level `README.md`, right at the beginning, so please follow those instructions. Orion and AWS pcluster have `fms@2022.04` installed.

@mer-a-o good point I need to update `README.md` with the new UFS_APP.

**Comment by jeromebarre** [comment]
ecbuild successful on Orion after loading the additional modules:
```
fms/2022.04 (swap as explained in the read me)
gftl-shared/1.5.0
mapl/2.22.0-esmf-8.3.0b09-esmf-8.3.0
bacio/2.4.1
sigio/2.3.2
w3emc/2.9.2
w3nco/2.4.1
nemsio/2.5.2
```

make is not successful:

```
[ 95%] Built target GOCART2G_GridComp
[ 95%] Built target Aerosol_GridComp
[ 98%] Built target UFS_Aerosols
[ 99%] Built target ufs
[100%] Linking Fortran executable ufs_model
/bin/ld: cannot find -lESMF
collect2: error: ld returned 1 exit status
make[5]: *** [ufs_model] Error 1
make[4]: *** [CMakeFiles/ufs_model.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ufs-weather-model/src/ufs-weather-model-stamp/ufs-weather-model-build] Error 2
make[1]: *** [CMakeFiles/ufs-weather-model.dir/all] Error 2
make: *** [all] Error 2 
```

```
module list esmf

Currently Loaded Modules Matching: esmf
  1) esmf/8.3.0b09   2) mapl/2.22.0-esmf-8.3.0b09-esmf-8.3.0`
```

sorry if i missed something again...

**Comment by mer-a-o** [comment]
I'm getting the same error as @jeromebarre.
```
Scanning dependencies of target ufs_model
[ 99%] Building Fortran object CMakeFiles/ufs_model.dir/driver/UFS.F90.o
[ 35%] Linking CXX executable test_l95_pseudomodel
[ 35%] Built target test_l95_pseudomodel
[ 35%] Building CXX object oops/l95/test/CMakeFiles/test_l95_increment.dir/executables/TestIncrement.cc.o
[100%] Linking Fortran executable ufs_model
[ 35%] Linking CXX executable test_l95_pseudomodel_state4d
[ 35%] Built target test_l95_pseudomodel_state4d
[ 35%] Building CXX object oops/l95/test/CMakeFiles/test_l95_errorcovariance.dir/executables/TestErrorCovariance.cc.o
/bin/ld: cannot find -lESMF
collect2: error: ld returned 1 exit status
make[5]: *** [ufs_model] Error 1
make[4]: *** [CMakeFiles/ufs_model.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ufs-weather-model/src/ufs-weather-model-stamp/ufs-weather-model-build] Error 2
make[1]: *** [CMakeFiles/ufs-weather-model.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Linking CXX executable test_l95_identitymodel
[ 35%] Built target test_l95_identitymodel
[ 35%] Linking CXX executable test_l95_increment
[ 35%] Built target test_l95_increment
[ 35%] Linking CXX executable test_l95_errorcovariance
[ 35%] Built target test_l95_errorcovariance
make: *** [all] Error 2
```

List of loaded modules:

```
Currently Loaded Modules:
  1) ecflow/5.8.4            18) jasper/2.0.32     35) openjpeg/2.3.1    52) libxmu/1.1.2                 69) py-mpi4py/3.1.4           86) py-beniget/0.4.1
  2) gcc/10.2.0              19) libpng/1.6.37     36) eccodes/2.27.0    53) libxpm/4.11.0                70) py-h5py/3.6.0             87) py-ply/3.11
  3) stack-gcc/10.2.0        20) g2/3.4.5          37) eigen/3.4.0       54) libxaw/1.0.13                71) py-cftime/1.0.3.4         88) py-pythran/0.11.0
  4) openmpi/4.0.4           21) g2tmpl/1.10.0     38) openblas/0.3.19   55) udunits/2.2.28               72) py-netcdf4/1.5.3          89) py-scipy/1.8.0
  5) stack-openmpi/4.0.4     22) sp/2.3.3          39) eckit/1.20.2      56) ncview/2.1.8                 73) py-bottleneck/1.3.5       90) py-xarray/2022.3.0
  6) miniconda/3.9.7         23) ip/3.3.3          40) fftw/3.3.10       57) netcdf-cxx4/4.3.1            74) py-pyparsing/3.0.9        91) jedi-base-env/1.0.0
  7) stack-python/3.9.7      24) cmake/3.22.1      41) fckit/0.9.5       58) json/3.10.5                  75) py-packaging/21.3         92) gftl-shared/1.5.0
  8) bacio/2.4.1             25) git/1.8.3.1       42) fiat/1.0.0        59) json-schema-validator/2.1.0  76) py-numexpr/2.8.3          93) yafyaml/0.5.1
  9) zlib/1.2.13             26) nccmp/1.9.0.1     43) ectrans/1.1.0     60) odc/1.4.5                    77) py-six/1.16.0             94) mapl/2.22.0-esmf-8.3.0b09-esmf-8.3.0
 10) curl/7.85.0             27) parallelio/2.5.7  44) atlas/0.31.1      61) py-attrs/22.1.0              78) py-python-dateutil/2.8.2  95) w3nco/2.4.1
 11) pkg-config/0.27.1       28) wget/1.14         45) gsibec/1.0.6      62) py-pycparser/2.21            79) py-pytz/2022.2.1          96) nemsio/2.5.2
 12) hdf5/1.12.1             29) base-env/1.0.0    46) gsl-lite/0.37.0   63) py-cffi/1.15.0               80) py-pandas/1.4.0           97) sigio/2.3.2
 13) parallel-netcdf/1.12.2  30) boost/1.72.0      47) krb5/1.15.1       64) py-findlibs/0.0.2            81) py-pybind11/2.8.1         98) w3emc/2.9.2
 14) netcdf-c/4.8.1          31) bufr/11.7.1       48) libtirpc/1.2.6    65) py-setuptools/59.4.0         82) py-pycodestyle/2.8.0      99) jedi-ufs-env/1.0.0
 15) netcdf-fortran/4.5.4    32) git-lfs/2.12.0    49) hdf/4.2.15        66) py-numpy/1.22.3              83) py-pyhdf/0.10.4          100) fms/2022.04
 16) esmf/8.3.0b09           33) crtm/v2.4-jedi.2  50) jedi-cmake/1.4.0  67) py-eccodes/1.4.2             84) py-pyyaml/6.0
 17) libjpeg/2.1.0           34) ecbuild/3.6.5     51) libxt/1.1.5       68) py-f90nml/1.4.3              85) py-gast/0.5.3
```

**Comment by climbfuji** [comment]
This one is on me (actually, no, but I should have remembered). It's a known, very complicated issue with how ESMF interacts with MAPL which interacts with esma_cmake, then add WW3 and GOCART, and all comes down that folks cannot agree if the cmake target (and library name) should be "esmf" or "ESMF". The workaround is to create symbolic links in the ESMF library installation in spack, which we are going to automate for the next spack-stack release, but so far we have to it manually. I did that on AWS, but not yet on Orion, so let me do this now ...

**Comment by climbfuji** [comment]
Fixed for both GNU and Intel on Orion, just rerun the make command please and let me know

**Comment by mer-a-o** [comment]
Thanks @climbfuji. I ran the make command again and got much further. I'm getting a different error now:
```
[ 93%] Built target test_autogeneratedfilter
[ 93%] Building CXX object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/VariableChange/ColdStartWinds/VarChaColdStartWinds.cc.o
[ 93%] Building CXX object ufo/tools/new_obsop/test/CMakeFiles/test_ufo_opr_autogenerated.dir/__/__/__/test/mains/TestObsOperator.cc.o
[ 93%] Building CXX object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/VariableChange/Control2Analysis/VarChaC2A.cc.o
[ 93%] Building CXX object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/VariableChange/GEOSRstToBkg/VarChaGeosRst2Bkg.cc.o
[ 93%] Building CXX object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/VariableChange/Model2GeoVaLs/VarChaModel2GeoVaLs.cc.o
[ 93%] Building CXX object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/VariableChange/VertRemap/VarChaVertRemap.cc.o
[ 93%] Building CXX object fv3-jedi/src/fv3jedi/CMakeFiles/fv3jedi.dir/Tlm/Tlm.cc.o
make[2]: *** No rule to make target `Depends/lib/libGA_Environment.a', needed by `lib/libfv3jedi.so'.  Stop.
```

**Comment by jeromebarre** [comment]
I have the same error too now.

**Comment by climbfuji** [comment]
> I have the same error too now.

The error message should be descriptive enough to check if the offending file exists or not, and if not if there was an error further up (if you ran with multiple make jobs).

**Comment by fcvdb** [comment]
I got the error too. The issue comes from the fact that the libraries:
```
libAerosol_GridComp.a
libCA2G_GridComp.a
libChem_Shared2G.a
libDU2G_GridComp.a
libGA_Environment.a
libGOCART2G_GridComp.a
libNI2G_GridComp.a
libProcess_Library.a
libSS2G_GridComp.a
libSU2G_GridComp.a
libUFS_Aerosols.a
```
Are built under `Depends/lib64`, but `cmake` is looking for them into `Depends/lib`.

I manually linked the `lib64` content into `lib` and the compilation completed. This is a hack, I'll look at the  `cmakefiles` to resolve the problem in a cleaner and more permanent way.

**Comment by climbfuji** [comment]
> I got the error too. The issue comes from the fact that the libraries:
> 
> ```
> libAerosol_GridComp.a
> libCA2G_GridComp.a
> libChem_Shared2G.a
> libDU2G_GridComp.a
> libGA_Environment.a
> libGOCART2G_GridComp.a
> libNI2G_GridComp.a
> libProcess_Library.a
> libSS2G_GridComp.a
> libSU2G_GridComp.a
> libUFS_Aerosols.a
> ```
> 
> Are built under `Depends/lib64`, but `cmake` is looking for them into `Depends/lib`.
> 
> I manually linked the `lib64` content into `lib` and the compilation completed. This is a hack, I'll look at the `cmakefiles` to resolve the problem in a cleaner and more permanent way.

Oh that's something I should be able to fix easily. Thanks @fcvdb !

**Comment by climbfuji** [comment]
I just pushed commit
```
commit d31ed6be5673043e6af39ab21d2461c5ab75f641 (HEAD -> feature/build_ufs_app_atmaero, dom/feature/build_ufs_app_atmaero)
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Thu Mar 2 11:51:56 2023 -0700

    Use correct install lib/include dir names in top-level CMakeLists.txt
```
which should fix the `lib64` vs `lib` problem. Can you try, please?

**Comment by jeromebarre** [comment]
> I just pushed commit
> 
> ```
> commit d31ed6be5673043e6af39ab21d2461c5ab75f641 (HEAD -> feature/build_ufs_app_atmaero, dom/feature/build_ufs_app_atmaero)
> Author: Dom Heinzeller <dom.heinzeller@icloud.com>
> Date:   Thu Mar 2 11:51:56 2023 -0700
> 
>     Use correct install lib/include dir names in top-level CMakeLists.txt
> ```
> 
> which should fix the `lib64` vs `lib` problem. Can you try, please?

I was about to comment about the same exact issue. I am trying now.

**Comment by jeromebarre** [comment]
`No rule to make target `Depends/lib64/libfv3atm.a', needed by `lib/libfv3jedi.so'` which is the opposite problem, now `libfv3atm.a` is in `Depends/lib`

**Comment by climbfuji** [comment]
> `No rule to make target `Depends/lib64/libfv3atm.a', needed by `lib/libfv3jedi.so'` which is the opposite problem, now `libfv3atm.a` is in `Depends/lib`

What a nonsense. We'd have to update all the jedi repos to do the right thing and put their libs in CMAKE_INSTALL_LIBDIR. I'll rather work around this in ufs-bundle, stay tuned.

**Comment by jeromebarre** [comment]
> > `No rule to make target `Depends/lib64/libfv3atm.a', needed by `lib/libfv3jedi.so'` which is the opposite problem, now `libfv3atm.a` is in `Depends/lib`
> 
> What a nonsense. We'd have to update all the jedi repos to do the right thing and put their libs in CMAKE_INSTALL_LIBDIR. I'll rather work around this in ufs-bundle, stay tuned.

I am trying to update the CMakelist to make it work. Could it just be a matter of pointing to lib for certain libraries?

**Comment by climbfuji** [comment]
> > > `No rule to make target `Depends/lib64/libfv3atm.a', needed by `lib/libfv3jedi.so'` which is the opposite problem, now `libfv3atm.a` is in `Depends/lib`
> > 
> > 
> > What a nonsense. We'd have to update all the jedi repos to do the right thing and put their libs in CMAKE_INSTALL_LIBDIR. I'll rather work around this in ufs-bundle, stay tuned.
> 
> I am trying to update the CMakelist to make it work. Could it just be a matter of pointing to lib for certain libraries?

No, that's messy and won't be enough on other systems. I think I'll have another fix for you to try soon.

**Comment by climbfuji** [comment]
Just pushed 42fb7e952e27f7afbe65e325c81d889a4670c5a1, are you able to try again? If it doesn't work, I'll take over tomorrow. Thanks!

**Review by fcvdb — DISMISSED** [review]
The build completed without error. 

There is a persisting warning (`Nonexistent include directory build/Depends/include_r8`) without impact. 

The following tests FAILED:
```
          8 - fv3jedi_test_tier1_geometry_lam_cmaq (Failed)
         15 - fv3jedi_test_tier1_geometry_iterator_lam_cmaq (Failed)
         24 - fv3jedi_test_tier1_state_lam_cmaq (Failed)
         25 - fv3jedi_test_tier1_state_lam_atmos (Failed)
         51 - fv3jedi_test_tier1_model_ufs_coldstart (Failed)
         56 - fv3jedi_test_tier1_forecast_ufs_coldstart (Failed)
         62 - fv3jedi_test_tier1_hofx_nomodel_lam_cmaq (Failed)
         69 - fv3jedi_test_tier1_bumpparameters_nicas_lam_cmaq (Failed)
         92 - fv3jedi_test_tier1_3dvar_lam_cmaq (Failed)
        101 - fv3jedi_test_tier1_4denvar (Failed)
        110 - fv3jedi_test_tier1_diffstates_lam_cmaq (Failed)
        139 - fv3jedi_test_tier2_staticb_nicas_gfs (Failed)
        141 - fv3jedi_test_tier2_staticb_split_nicas_gfs (Failed)
        142 - fv3jedi_test_tier2_staticb_dirac_local_gfs_6pe (Failed)
        143 - fv3jedi_test_tier2_staticb_dirac_local_gfs_12pe (Failed)
        144 - fv3jedi_test_tier2_staticb_dirac_global_gfs_6pe (Failed)
        145 - fv3jedi_test_tier2_staticb_dirac_global_gfs_12pe (Failed)
        161 - fv3jedi_test_tier2_hofx_nomodel_lam_rrfs (Failed)
        165 - fv3jedi_test_tier2_hyb-3dvar_gfs (Failed)
        168 - fv3jedi_test_tier2_eda_4dvar_fv3lm (Failed)

```
But it seems that for most, the input data are missing.

**Comment by climbfuji** [comment]
Thanks @fcvdb ! The `_ufs_` tests most likely failed because they were designed for the `ATM`-only configuration. Seems I need to update the tests in `fv3-jedi` to look for an exact match of the `UFS_APP`, not a partial match.

**Comment by climbfuji** [comment]
> Thanks @fcvdb ! The `_ufs_` tests most likely failed because they were designed for the `ATM`-only configuration. Seems I need to update the tests in `fv3-jedi` to look for an exact match of the `UFS_APP`, not a partial match.

Ok, my latest updates to the feature/ufs_dom branch in fv3-jedi and to this PR should remove the warnings about the non-existent include_r8 directory, and only run the currently available ufs tests for UFS_APP=ATM. For ATMAERO, you'll get a warning in the ecbuild log saying that there are no ctests configured for ATMAERO.

**Comment by shlyaeva** [comment]
🎉 That's exciting! I'll remove myself from reviewers since there are enough reviewers already, but please ping me if my review is needed.

**Comment by jeromebarre** [comment]
Build successful on Orion, thanks @climbfuji !

**Review by jeromebarre — DISMISSED** [review]

**Review by cmgas — DISMISSED** [review]
Built fine on Orion! Could you update the ReadMe too?

**Comment by climbfuji** [comment]
> Built fine on Orion! Could you update the ReadMe too?

Of course. Let me do that now and then merge. Thanks for the reminder!

**Comment by climbfuji** [comment]
@cmgas @jeromebarre Unfortunately I need to have you approve again after I updated `README.md`

**Review by jeromebarre — APPROVED** [review]

**Review by cmgas — APPROVED** [review]
👍

**Pull request merged**
