### PR TITLE
Switch CI to spack-stack-1.5.0

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Update software stack to spack-stack-1.5.0. To fix a compilation problem for ATMAERO, I had to push a small change to the fv3-jedi branch feature/ufs_dom (https://github.com/JCSDA-internal/fv3-jedi/commit/288a9288124314d5cb21e297ee66f70ef5ba3dcd) - see https://github.com/GEOS-ESM/GOCART/pull/254 for more information.

## Issue(s) addressed

n/a

## Dependencies

n/a

## Impact

n/a

## Checklist

- [x] I have performed a self-review of my own code
- [ ] ~~I have made corresponding changes to the documentation~~
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by climbfuji** [comment]
Ohhh this is almost funny ... this requires a workaround in GOCART, for which I already have a branch in the ufs-weather-model. Might as well cherry-pick that commit so that future merges of the authoritative branches will be easier.

**Comment by climbfuji** [comment]
There is a PR for ufs-weather-model from a temporary branch to the branch used in ufs-bundle that needs to be merged if/once the regression tests pass, then the change of the branch name in `CMakeLists.txt` can be reverted:

https://github.com/climbfuji/ufs-weather-model/pull/14

**Review by shlyaeva — APPROVED** [review]
Approving based on tests passing; sounds like lots of interesting debugging.. Thank you @climbfuji !

**Review by cmgas — APPROVED** [review]
Thanks Dom!

**Pull request merged**
